
namespace ItemAPI.EnumConverters {

    public static class ClassTypeEnumConverter {

        public static string ConvertClassType(this int classId) {

            return classId switch {
                0 => "Misc" ,
                95 => "Double Axe" ,
                9 => "Double Sword" ,
                98 => "Double Dirks" ,
                99 => "[ ClassEnum error: 99 ]" ,
                100 => "Other Weapons; Not exist" ,
                101 => "One-Handed Sword" ,
                102 => "Two-Handed Sword" ,
                103 => "Dagger" ,
                104 => "Spear" ,
                105 => "Two Handed Axe" ,
                106 => "One Handed Mace" ,
                107 => "Two Handed Mace" ,
                108 => "Longbow" ,
                109 => "[ ClassEnum error: 109 ]" ,
                110 => "Crossbow" ,
                111 => "One-Handed Staff" ,
                112 => "Two-Handed Staff" ,
                113 => "One-Handed Axe" ,
                200 => "Common armor" ,
                201 => "Warrior armor" ,
                202 => "Hunter armor" ,
                203 => "Magician armor" ,
                204 => "Summoner armor" ,
                210 => "Common shield" ,
                220 => "Common helmet" ,
                230 => "Common boots" ,
                231 => "Warrior boots",
                232 => "Hunter boots" ,
                233 => "Magician boots" ,
                234 => "Summoner boots" ,
                240 => "Common gloves" ,
                241 => "Warrior gloves",
                242 => "Hunter gloves" ,
                243 => "Magician gloves" ,
                244 => "Summoner gloves" ,
                250 => "Common belt" ,
                251 => "Warrior belt",
                252 => "Hunter belt" ,
                253 => "Magician belt" ,
                254 => "Summoner belt" ,
                260 => "Common mantle" ,
                261 => "Warrior mantle",
                262 => "Hunter mantle" ,
                263 => "Magician mantle" ,
                264 => "Summoner mantle" ,
                265 => "Quiver" ,
                266 => "Booster Slot" ,
                300 => "guitar accessories" ,
                301 => "Ring" ,
                302 => "Earrings" ,
                303 => "Necklace" ,
                304 => "Face equip slot; calls \"face\"" ,
                305 => "[ ClassEnum error: 305 ]",
                306 => "[ ClassEnum error: 306 ]",
                400 => "Chips (Luna, Force, Soul)" ,
                401 => "Soul Stone" ,
                402 => "Animal Cracker" ,
                403 => "Creature stable pass" ,
                502 => "HV pass & all-in-one-deathmatch-potion" ,
                600 => "deprecated" ,
                601 => "Decorative Shield" ,
                602 => "Decorative Armor" ,
                603 => "Decorative Head" ,
                604 => "Decorative Gloves" ,
                605 => "Decorative Boots" ,
                606 => "Decorative Cape" ,
                607 => "Wings" ,
                608 => "Hairstyle" ,
                609 => "Decorative One Handed Sword" ,
                610 => "Decorative Two Handed Sword" ,
                611 => "Decorative Dirk" ,
                612 => "Decorative Spear" ,
                613 => "Decorative Two Handed Axe" ,
                614 => "Decorative One Handed Mace" ,
                615 => "Decorative Two Handed Mace" ,
                616 => "Longbow deco?" ,
                617 => "[ ClassEnum error: 617 ]",
                618 => "Decorative Crossbow/XBow" ,
                619 => "Decorative One Handed Staff" ,
                620 => "Decorative Two Handed Staff" ,
                621 => "Decorative One Handed Axe" ,
                700 => "Jewels; Elite shards",
                _ => $"[ ClassEnum error: {classId} ]",
            };

        }
    }

}
